### ISSUE TITLE
Session simulator component

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1672]
Create a backend component or agent that given a questionnaire it will be able to handle in-memory sessions for different respondents.

Each session is independent and the goal is to persist nothing in the db. `Flow` and `Sessions` are the one with the semantics to move advance the state of the respondent.

Check that there is a way to extract the information to be shown in https://projects.invisionapp.com/d/main#/console/8374235/385278474/preview
* disposition
* questions state
* messages

This issue is for devolping the component and unit testing it. No need to integrate with the UI or expose it in the API,

**Comment by anaPerezGhiglia** [comment]
## TODO list after #1696 

 - [ ] Currently the questionnaire is being adapted (from there its limitations with sections), and “sms_simulator” mode is used. Check if it is possible to not adapt the questionnaire but instead, use “sms” mode and use the questionnaire as-it-is (change in `QuestionnaireSimualtor` and `SMSSimulatorMode`). 
    - [ ] If the above is not possible, adapt questionnaire so it take into account the sections - use `Questionnaire.all_steps` function

- [ ] Respondent is being created with `disposition: queued`. Why is not being transitioned to `contacted` after starting the session and sending the first reply? According the [dispositions diagram](https://drive.google.com/file/d/0B21iplh0ozbVZTBYdXJ2RjZxMTQ/view) it should. Currently is transitioning from `queued` to `started`

- [ ] Implement logic to support __interim-partial by relevant steps__ feature. It doesn’t work since fetches responses from db

- [ ] When questionnaire doesn’t have a `thank-you-message` the last respondent-response isn’t registered in submissions field (because `{:end, respondent}` instead of `{:end, reply, respondent}`)

- [ ]  `QuestionnaireController` Should return 404 if questionnaire is empty (because does not belong to that project)

- [ ] Validate if questionnaire has “sms” as mode before launching simulation

- [ ] `RetriesHistogram` should not be created and modified for in-memory sessions

Off-topic but necessary
 - [ ] Change `Session.start` optional parameters to a map (_long-parameter-list_)
