### ISSUE TITLE
Create pending unit tests for questionnaire import/export

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1988]
The questionnaire export and export CSV features were created for a much simpler version of the questionnaires than the one we have now (Nov - 2021). Then we did several patches to that process and added a few tests but it remains unstable, small (and not so) bugs are continuously appearing.
We should add a set of unit tests to the questionnaire and the questionnaire export.

Some known issues:
- [x] There are several cases in which audio files are not exported (see #1996)
- [x] The CSV export does not include steps inside randomized sections (see #1995)
- [x] The questionnaire doesn't show any issue when it has no audio (nor TTS) in a step

**Comment by ysbaddaden** [comment]
I started looking at exporting questionnaires.

1. The ZIP export crashes in staging should be fixed by #1996 (issue #1997).

2. The CSV export/import is purely in JS (I was surprised) and has [some tests](https://github.com/instedd/surveda/blob/master/test/js/reducers/questionnaire.spec.js#L2779-L2935) already. If I understand correctly, it's only for handling translations?

   I'm not sure what feature is missing. I'll dig a little more.

3. Looking deeper I notice that the ZIP export has some internal tests, but there are no tests at the actual API endpoint, validating that the API is working.

4. AFAIK there are zero tests for importing a previously exported ZIP.

**Comment by ysbaddaden** [comment]
1. I can now export questionnaires as ZIP in staging :)
2. I still can't reproduce any issue with the CSV export/import. I have yet to verify what's missing in the existing test suite to ensure that all features are supported.

**Comment by ysbaddaden** [comment]
I identified and reproduced the following issues:

1. With **SMS messages with split parts**: only the first part is exported, while the n+1 are skipped;
2. If the `#` character appears in a message, the CSV will stop being generated just before it.

**Comment by diegoliberman** [comment]
No more cases
